### ISSUE TITLE
Add AreaRepository

### ISSUE THREAD

**Issue by Muirrum** [Dev-Osmium/text-adventure-engine#4]
Just a way to keep track of areas. Should have an ArrayList of Areas that can be accessed and updated.

**Comment by TomerPacific** [comment]
@Dev-Osmium , can you give a bit more information on this issue. Where is this object supposed to be? Do you want an entirely new class? Should it be part of another class? What methods would you like exposed? Who are the consumers for this object?

**Comment by Muirrum** [comment]
@TomerPacific I would put it in something like AreaRepository.java, unless you think there's a better place. Basically just a way to store a list of areas. Maybe it would be better put in the Game class?

**Comment by iqueso** [comment]
You intend to connect this to a JSON/SQLLite database, right? Are you looking to pull from that database from the repository, or are you going to design a context/entity manager too?

**Comment by JessieVela** [comment]
@Dev-Osmium I can give this a try. You can go ahead and assign me.
Is the AreaRepository containing all possible areas in the game?

**Comment by Muirrum** [comment]
@JessieVela It should. Just as a simple way to get at them. Something I forgot to mention that I'm going to put here is it should be able to search by name and/or assign an ID.

@iQu3so I wasn't planning on it. I was going to have locations programmatically defined.

**Comment by JessieVela** [comment]
@Dev-Osmium okay got it. Last question, I noticed the Location class and it has some interaction with Area class. What exactly is Location and how is this supposed to interact with Area?

**Comment by Muirrum** [comment]
A `Location` defines a single room in the world. It has a name, a description, and contents. An `Area` is a way of sorting those Locations into a defined organization. Each Area has one or more Locations.

**Comment by JessieVela** [comment]
Should we make location dependent on area? Meaning you can't create a stand alone location without residing in an area.

**Comment by Muirrum** [comment]
Honestly right now I'm kinda debating whether to keep areas. Currently it's impossible to create a Location without specifying an area (see the Location constructor). I think that Areas would overcomplicate things

**Comment by JessieVela** [comment]
Having that issue right now. I found I would have to rewrite alot of the location class.

**Comment by Muirrum** [comment]
Thanks for the help @JessieVela ! Feel free to move on to another issue if you want.

**Comment by Muirrum** [comment]
@all-contributors please add @JessieVela for code
